name: "Bug Report"
description: "Report a bug or crash in the modpack"
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you submit
        Please make sure to check if this issue has already been reported.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-report Checklist
      options:
        - label: I have searched the existing issues to ensure this is not a duplicate.
          required: true
        - label: I have tried temporarily removing my custom additions to see if they cause the issue.
          required: true

  - type: input
    id: modpack-version
    attributes:
      label: Modpack Version
      description: "Enter the version number of the pack you are playing."
      placeholder: "0.0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Summary
      description: "What went wrong? Be as descriptive as possible."
      placeholder: "I was placing a block, and the game crashed..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: "How can I trigger this bug?"
      placeholder: "1. Do this...\n2. Then do that..."
    validations:
      required: true

  - type: checkboxes
    id: custom-mods
    attributes:
      label: Additional Info
      options:
        - label: Custom mods installed
          required: false

  - type: dropdown
    id: launcher
    attributes:
      label: Launcher
      description: "Which launcher are you using to play the pack?"
      options:
        - Prism Launcher
        - Modrinth App
        - CurseForge App
        - Other
    validations:
      required: true

  - type: upload
    id: latest-log
    attributes:
      label: Latest Log File
      description: |
        Optionally upload your `/logs/latest.log` file.
    validations:
      required: false
      accept: ".log,.txt"
